-- VIEW ALL TABLES AVAILABLE IN THE DATABASE
SHOW TABLES;

-- VIEW CUSTOMER DIMENSION DATA
SELECT *
FROM dim_customers;

-- VIEW PRODUCT DIMENSION DATA
SELECT *
FROM dim_products;

-- VIEW SALES FACT DATA
SELECT *
FROM fact_sales;
