-- LIST OF UNIQUE CUSTOMER COUNTRIES
SELECT DISTINCT country
FROM dim_customers;

-- LIST OF UNIQUE CUSTOMER GENDERS
SELECT DISTINCT gender
FROM dim_customers;

-- LIST OF UNIQUE PRODUCT NAMES
SELECT DISTINCT product_name
FROM dim_products;

-- LIST OF UNIQUE PRODUCT CATEGORIES
SELECT DISTINCT category
FROM dim_products;
