-- TOTAL CUSTOMERS BY COUNTRY
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY country;

-- TOTAL CUSTOMERS BY GENDER
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY gender;

-- TOTAL PRODUCTS BY CATEGORY
SELECT
    category,
    COUNT(product_key) AS total_products
FROM dim_products
GROUP BY category;

-- AVERAGE PRODUCT COST BY CATEGORY
SELECT
    category,
    AVG(cost) AS average_cost
FROM dim_products
GROUP BY category;

-- TOTAL REVENUE GENERATED BY PRODUCT CATEGORY
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales f
LEFT JOIN dim_products p
    ON f.product_key = p.product_key
GROUP BY p.category;

-- TOTAL ITEMS SOLD BY COUNTRY
SELECT
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM fact_sales f
LEFT JOIN dim_customers c
    ON f.customer_key = c.customer_key
GROUP BY c.country;
